[package]
name = "nso-param-search"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nxo-parser = { git = "https://github.com/jam1garner/nxo-parser.git" }
binread = "1.4"
yaxpeax-arm = "0.0.6"
yaxpeax-arch = "0.0.4"
